name = "aa-reflect-todo"
main = "worker/index.ts"
compatibility_date = "2022-06-03"


[durable_objects]
bindings = [
  { name = "roomDO", class_name = "RoomDO" },
  { name = "authDO", class_name = "AuthDO" }
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["RoomDO", "AuthDO"]

[triggers]
crons = [ "*/5 * * * *" ] # ever 5 mins for AuthDO connection revalidation